---
name: Build Arch Linux Package
description: Build Archlinux / Manjaro package with Docker, auto resolve AUR dependencies, for AMD64 or ARM64
branding:
  icon: package
  color: blue
inputs:
  platform:
    description: The platform (architecture) to build. Possible values are "linux/amd64" and "linux/arm64".
    required: false
    default: linux/amd64

  pkg_builds_repo:
    default: 'nemomobile-ux/nemo-packaging'
  pkg_build_path:
    description: the name of directory in pkg_builds_repo where the PKGBUILD is for example lipstick-glacier-home-git
  overlay_repo_url:
    default: 'https://nemo.mlich.cz/build-results-x86_64/packages/'
  overlay_repo_name:
    default: 'nemomobile'
  extra_packages:
    decription: list of packages to be installed before build to avoid conficts

outputs:
  skipped:
    description: Indicate if the build is skipped since the package already exists in the repo.
    value: ${{ steps.build.outputs.skipped }}
runs:
  using: "composite"
  steps:
    - name: Checkout packaging
      uses: actions/checkout@v3
      with:
        repository: ${{ pkg_builds_repo }}
        fetch-depth: 0
        path: ./nemo-packaging
    - name: Prepare environment
      env:
        OVERLAY_REPO_URL: ${{ overlay_repo_url }}
        OVERLAY_REPO_NAME: ${{ overlay_repo_name }}
        EXTRA_PACKAGES: ${{ extra_packages }}
      run: |
        sed -i "s|^\[core\]|\["$OVERLAY_REPO_NAME"\]\nSigLevel = Optional TrustAll\nServer = "$OVERLAY_REPO_URL"\n\n\[core\]|" /etc/pacman.conf
        sed 's/OPTIONS=.*/OPTIONS=(!strip docs !libtool !staticlibs emptydirs zipman purge debug)/' -i /etc/makepkg.conf
        pacman-mirrors -B unstable --geoip --api
        pacman -Syyuu --noconfirm
        pacman -Sy --noconfirm base-devel manjaro-release manjaro-tools manjaro-arm-tools wget
        pacman -Sy --noconfirm $EXTRA_PACKAGES
        echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
    - name: Build
      env:
        PKG_BUILD_PATH: ${{ pkg_build_path }}
      run: |
        mkdir -p ./build/src
        cd ./build
        ln ../nemo-packaging/${PKG_BUILD_PATH}/PKGBUILD ./PKGBUILD
        sed "s|::git+\${url}|::git+"${GITHUB_SERVER_URL}"/"${GITHUB_REPOSITORY}"#commit="${GITHUB_SHA}"|" -i PKGBUILD
        chown -R builder:builder .
        su builder -c 'makepkg -f --syncdeps --noconfirm'
    - name: Archive build results
      uses: actions/upload-artifact@v2
      with:
        path: ./build/*.pkg.tar.zst
